name: Node.js CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Use Node.js 20.x
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    - name: Install dependencies
      run: npm install

    - name: Start services and run tests
      run: |
        # Inicia a API REST em background
        npm start-rest &
        
        # Inicia a API GraphQL em background
        npm start-graphql &
        
        # Espera as APIs estarem prontas
        sleep 5
        
        # Configura as variáveis de ambiente localmente
        export BASE_URL_REST="http://localhost:3000"
        export BASE_URL_GRAPHQL="http://localhost:4000/graphql"
        
        # Executa os testes de API REST
        npm run test-rest-external
        
        # Executa os testes de API GraphQL
        npm run test-graphql-external